# Generated by Django 2.0.8 on 2018-11-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copydata',
            name='date',
            field=models.CharField(default='nodate', max_length=40),
        ),
    ]
